---
title: "Clusters"
author: "Jose Pablo Gómez Mata"
date: "6/10/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Referencias:

Por que utilice la correlacion: https://arxiv.org/pdf/1601.02213.pdf 

# librerias
```{r}
library(tensorflow)
library(keras)
library(tidyverse)
library(caret) 
library(ggplot2)
library(ggpubr)
library(grid)
library(cluster)
library(factoextra)
```
 
# carga de la base de datos 

```{r}
# load('bases_analisis.RData')
# base <- bases_ent %>% reduce(rbind)

load("datos_totales.Rdata")
base <- datos_totales

head(base)

base_cor = select(base,Year,Month,Canton,RR)
base_cor = as.data.frame(base_cor)
base_cor$RR = as.numeric(base_cor$RR)
base_cor$fecha = paste(base_cor$Year,"/",base$Month)
base_cor <- select(base_cor,fecha,Canton,RR)

df <- base_cor %>% pivot_wider(names_from = fecha,
                               values_from = RR,
                               values_fill = 0)
df <- as.data.frame(df)
rownames(df) <- c(df$Canton)

```

# matriz de distancias (correlaciones de pearson)

Como me interesa observar los patrones del riesgo relativo para los cantones utilizo la distancia de correlaciones

```{r}
df <- df[,-1]
df2 <- t(df)
df2[is.na(df2)] <- 0
d_corr <- cor(df2)
dist <- 1-d_corr
dist <- as.dist(dist)
```


# matriz de distancias (euclidea)

```{r}
d_e <- dist(df)
```


# clusters

```{r}
# Distancias entre individuos utilizando correlaciones

# Con el vecino mas cercano
d1_s <- hclust(dist, method = "single")
plot(d1_s, xlab = "", main = "Vecino mas cercano con correlacion", ylab = "Distancia", sub
= "")

# Con el vecino mas lejano
d1_c <- hclust(dist, method = "complete")
plot(d1_c, xlab = "", main = "Vecino mas lejano con correlacion", ylab = "Distancia", sub
= "")

# Con el salto promedio
d1_a <- hclust(dist, method = "average")
plot(d1_a, xlab = "", main = "Salto promedio con correlacion", ylab = "Distancia", sub
= "")

# Con la distancia de Ward
d1_w <- hclust(dist, method = "ward.D")
plot(d1_w, xlab = "", main = "Distancia de Ward con correlacion", ylab = "Distancia", sub
= "")

# Distancias entre individuos utilizando la distancia Euclidea

# Con el vecino mas cercano
de1_s <- hclust(d_e, method = "single")
plot(de1_s, xlab = "", main = "Vecino mas cercano con la distancia Euclidea", ylab = "Distancia", sub
= "")

# Con el vecino mas lejano
de1_c <- hclust(d_e, method = "complete")
plot(de1_c, xlab = "", main = "Vecino mas lejano con la distancia Euclidea", ylab = "Distancia", sub
= "")

# Con el salto promedio
de1_a <- hclust(d_e, method = "average")
plot(de1_a, xlab = "", main = "Salto promedio con la distancia Euclidea", ylab = "Distancia", sub
= "")

# Con la distancia de Ward
de1_w <- hclust(d_e, method = "ward.D")
plot(de1_w, xlab = "", main = "Distancia de Ward con la distancia Euclidea", ylab = "Distancia", sub
= "")

```


```{r}
fviz_dend(x=d1_w,k=4,cex=0.8)+geom_hline(yintercept=1.98,linetype="dashed")+
 labs(title="Distancia de correlacion y metodo de agrupamiento de Ward")+aes(y=Distancia)
```




