---
title: "Validación Cruzada"
author: "Jimena Murillo Montero"
date: '2022-08-31'
output: html_document
---

### Paquetes

Se llaman los paquetes a utilizar.

```{r setup, include=FALSE}
library(keras) # for deep learning
library(tidyverse) # general utility functions
library(caret) # machine learning utility functions
library(tibble)
library(readr)
library(ggplot2)
library(tensorflow)
library(neuralnet)
library(grid)
library(lubridate)
library("writexl")

```


## Datos


```{r}
load("C:/Users/usuario1/Desktop/CIMPA/Github_CIMPA/PRACTICA_CIMPA/base_cantones.RData")

basecanton = basecanton  %>% 
  
  dplyr::select(Canton, Year,Month,Nino34SSTA1, Nino34SSTA2, Nino34SSTA3, Nino34SSTA4, Nino34SSTA5, Nino34SSTA6, TNA1,TNA2, NDVI1, NDVI2, LSD1, LSD2, Precip_t1, Precip_t2, Precip_t3, Precip_t4, Precip_t5, Precip_t6, RRl1, RR) %>% 
  
  arrange(Canton,Year,Month) %>% ungroup() %>% mutate(Month=as.numeric(Month))

Cantones = unique(basecanton$Canton)




### Funciones ###

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
denorm <- function(x,base) {
  a = (x*(max(base$RR) - min(base$RR))+min(base$RR))
  return = a
}


 nrmse <- function(tabla){
    NRMSE <- mean((tabla$y_pred-tabla$RR)^2)/mean(tabla$RR)
    return(data.frame(NRMSE))
 }
 
 nis <- function(tabla){
    NIS_95 <- mean((tabla$LS-tabla$LI)+
                   (2/0.05)*(tabla$LI-tabla$RR)*(tabla$RR<tabla$LI)+
                   (2/0.05)*(tabla$RR-tabla$LS)*(tabla$RR>tabla$LS))/mean(tabla$RR)
    return(data.frame(NIS_95))
 }
 
 
  
predice = function(x) {
  y_values = (model %>% predict(x))
  result = (y_values*(max(base$RR) - min(base$RR))+min(base$RR))
  return (as.numeric(result))
}





### Normalizar ###

basecanton2 = basecanton %>% group_by(basecanton$Canton) %>% 
  mutate_if(is.numeric, normalize)
basecanton2 = basecanton2[,-24]

#Clusters

Grupos = list()
Grupos[[1]] = Cantones[c(1,3,26)]
Grupos[[2]] = Cantones[c(2,7,25)]
Grupos[[3]] = Cantones[c(4,12,13)]
Grupos[[4]] = Cantones[c(5,17,27)]
Grupos[[5]] = Cantones[c(8,16,23)]
Grupos[[6]] = Cantones[c(14,15)]
Grupos[[7]] = Cantones[c(21,30)]
Grupos[[8]] = Cantones[c(11,22,29)]
Grupos[[9]] = Cantones[c(28,31)]
Grupos[[10]] = Cantones[c(9,18,24)]
Grupos[[11]] = Cantones[c(6,10)]
Grupos[[12]] = Cantones[c(19,20,32)]

#Train y test
X_data = as.data.frame(basecanton2) 
X_data = X_data[,-ncol(X_data)]

y_data = as.data.frame(basecanton2)
y_data = y_data[,c("Canton", "Year","Month","RR")]

Fecha = paste(basecanton$Year, basecanton$Month)
Fecha = Fecha[1:235]
Mes = basecanton$Month
Mes = Mes[1:235]


```


## Arquitectura del modelo


```{r}
model <- keras_model_sequential()
# our input layer
model %>% 
    layer_simple_rnn(units = 100, input_shape = c(ncol(X_data)-1,1), activation='tanh', 
                   kernel_initializer= initializer_constant(0.5),
                   bias_initializer=initializer_zeros()) %>% 
  layer_dense(units = 50, activation = "relu")%>%
  layer_dense(units = 50, activation = "relu")%>%
  layer_dense(units = 50, activation = "relu")%>%
  layer_dropout(rate = 0.1)%>%
  layer_dense(units = 25, activation = "relu")%>%
  layer_dense(units = 25, activation = "relu")%>%
  layer_dense(units = 25, activation = "relu")%>%
  layer_dropout(rate = 0.1)%>%
  layer_dense(units = 12, activation = "relu")%>%
  layer_dense(units = 12, activation = "relu")%>%
  layer_dropout(rate = 0.1)%>%
  layer_dense(units = 6, activation = "relu")%>%
  layer_dense(units = 6, activation = "relu")%>%
  
  layer_dense(units = 1, activation = "sigmoid")

```


# Validación tipo 2 2018-2021

## Entrenamiento y predicciones

```{r}
    
Metricas = matrix(nrow = length(Cantones), ncol = 4)
M_trimestre1 = matrix(nrow = length(Cantones), ncol = 4)
M_trimestre2 = matrix(nrow = length(Cantones), ncol = 4)
M_trimestre3 = matrix(nrow = length(Cantones), ncol = 4)
M_trimestre4 = matrix(nrow = length(Cantones), ncol = 4)

Index = c(1,4,7,10,13,16,18,20,23,25,28,30)

val_a = unique(X_data$Year)[c(18,19,20,21)]
val_a = rep(val_a, each = 4)
val_a = val_a[-c(14:16)]

val_m = sort(unique(X_data$Month))
val_indx = rep(c(1,4,7,10), 4)
val_indx = val_indx[-c(14:16)]

for (i in 1:length(Grupos)) {
  
  X_grupo = X_data %>% filter(Canton %in% Grupos[[i]])
  y_grupo = y_data %>% filter(Canton %in% Grupos[[i]])
  
  
  NRMSE_test = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
  NIS_test = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
      
  NRMSE_total = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
  NIS_total = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
  

  for (v in 1:length(val_a)) {
    
    Xtrain = X_grupo %>% filter(Year < val_a[v])
    Xtrain = rbind(Xtrain, h=X_grupo %>% filter(Year == val_a[v] & Month < val_m[val_indx[v]]))
    
    ytrain = y_grupo %>% filter(Year < val_a[v])
    ytrain =  rbind(ytrain, y_grupo %>% filter(Year == val_a[v] & Month < val_m[val_indx[v]]))
    
    Xtest = X_grupo %>% filter(Year == val_a[v] & Month %in% val_m[val_indx[v]:(val_indx[v]+2)] )
    ytest = y_grupo %>% filter(Year == val_a[v] & Month %in% val_m[val_indx[v]:(val_indx[v]+2)] )
    
    
    model %>% compile(loss = "mse", 
                      optimizer = optimizer_adam(lr = 0.0005),
                      metric = "mean_absolute_error")
    
    trained_model <- model %>% fit(
      x =  as.matrix(Xtrain[,-1]), 
      y = as.matrix(ytrain[,c("RR")]), 
      batch_size = 18, 
      epochs = 30, 
      validation_split = 0.1,
      shuffle = F) 
    
  
    for (j in 1:length(Grupos[[i]])) {
      

      pred = NULL
      
      xtr = Xtrain %>% filter(Canton == Grupos[[i]][j])
      xtr = as.matrix(xtr[,-1])
      
      xts = Xtest %>% filter(Canton == Grupos[[i]][j])
      xts = as.matrix(xts[,-1])
      
      base = data.frame(basecanton2 %>% filter(Canton == Grupos[[i]][j]) %>% dplyr::select(RR))
    
      yts = as.matrix(denorm((ytest %>% filter(Canton == Grupos[[i]][j]))[,-c(1,2,3)], base))
        
      # predicciones a 3 meses
      for (k in 1:2) {
        pred[k] = predice(xts)[k]
        xts[k+1,21] = pred[k]
      } 
      pred[3] = predice(xts)[3]
      
      
     
      # Se crea una base para las predicciones, "df1", que tiene los valores predichos, los valores reales, fecha y mes.
      df1 = as.data.frame(cbind(pred, 
                                yts, 
                                Fecha[(nrow(xtr)+1):(nrow(xtr)+3)],
                                Mes[(nrow(xtr)+1):(nrow(xtr)+3)]))
      colnames(df1) = c("y_pred", "RR", "Fecha","Mes")
      df1$RR = as.numeric(df1$RR)
      df1$y_pred = as.numeric(df1$y_pred)
      
    
     
      #### VALORES APROXIMADOS ####
      ## Generar valores ajustados
      
      df2 = as.data.frame(cbind(predice(xtr), 
                                base$RR[1:nrow(xtr)], 
                                Fecha[1:nrow(xtr)], 
                                Mes[1:nrow(xtr)]))
      colnames(df2) = c("y_pred", "RR", "Fecha","Mes")
      df2$RR = as.numeric(df2$RR)
      df2$y_pred = as.numeric(df2$y_pred)
      df2 = rbind(df2, df1)
      
     # everyother1 <- function(x) x[(seq_along(Fecha) + 5)%%12 == 6]
      
      # aqui hago las predicciones del 2000 hasta el 2020 con intervalos de bootstrap
      
    LI = matrix(ncol = 1, nrow = nrow(df2))
    LS = matrix(ncol = 1, nrow = nrow(df2))
    for (w in 1:12) {

      indx = which(df2$Mes== w)
      x <- df2[Mes==w,1] # tomo el mes w con las predicciones para cada mes (es decir que tomo el mes w para los años que hayan reportados)
      x <- as.numeric(na.omit(x))
      n <- length(x) # voy a hacer un remuestreo para la cantidad de observaciones que tenga de ese mes w
      Tn <- mean(x) # saco la media para estos datos
      
      B <- 100
      Tboot_b <- NULL
      for(b in 1:B) {  
        xb <- sample(x, size = n, replace = TRUE)  
        Tboot_b[b] <- mean(xb)
      }
      # calculo de estadisticos de bootstrap
      Tboot <- mean(Tboot_b)
      Vboot <- var(Tboot_b)
      sdboot <- sqrt(Vboot)
      
      # ahora el IC de bootstrap estudentizado
      B <- 300
      Tboot_b <- NULL
      Tboot_bm <- NULL
      sdboot_b <- NULL
      
      for (b in 1:B) {  
        xb <- sample(x, size = n, replace = TRUE)  
        Tboot_b[b] <- mean(xb) # la media
        for (m in 1:B) {    
          xbm <- sample(xb, size = n, replace = TRUE)    
          Tboot_bm[m] <- mean(xbm)  
        }  
        sdboot_b[b] <- sd(Tboot_bm)
      }
      
      z_star <- (Tboot_b - Tn) / sdboot_b
      
      # se crean los limites inferiores y superiores
      LI[indx,] = x - quantile(z_star, 1 - 0.05 / 2) * sdboot
      LS[indx,] = x - quantile(z_star, 0.05 / 2) * sdboot
    }
    
      
      
      
      #Añadir límites a la base df2
      
    
      df2 = cbind(df2, LI, LS)
      df1 = cbind(df1, LI[(nrow(xtr)+1):(nrow(xtr)+3)], 
                  LS[(nrow(xtr)+1):(nrow(xtr)+3)])
      colnames(df1) = c("y_pred","RR","Fecha","Mes","LI","LS")
    
      
      NRMSE_test[j,v] = as.numeric(nrmse(df1))
      
      NIS_test[j,v] = as.numeric(nis(df1))
      
      NRMSE_total[j,v] = as.numeric(nrmse(df2))

      NIS_total[j,v] = as.numeric(nis(df2))
  
    }
    
   k_clear_session()
   
  }
  

  
  Metricas[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = cbind( rowMeans((NRMSE_test*is.finite(NRMSE_test)), na.rm=TRUE), 
rowMeans((NIS_test*is.finite(NIS_test)), na.rm=TRUE), 
rowMeans((NRMSE_total*is.finite(NRMSE_total)), na.rm=TRUE),
rowMeans((NIS_total*is.finite(NIS_total)), na.rm=TRUE))
  
  
  M_trimestre1[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = cbind(rowMeans((NRMSE_test[,c(1,5,9,13)]*is.finite(NRMSE_test[,c(1,5,9,13)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(1,5,9,13)]*is.finite(NIS_test[,c(1,5,9,13)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(1,5,9,13)]*is.finite(NRMSE_total[,c(1,5,9,13)])), na.rm=TRUE),
rowMeans((NIS_total[,c(1,5,9,13)]*is.finite(NIS_total[,c(1,5,9,13)])), na.rm=TRUE))
  
   M_trimestre2[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = cbind(rowMeans((NRMSE_test[,c(2,6,10)]*is.finite(NRMSE_test[,c(2,6,10)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(2,6,10)]*is.finite(NIS_test[,c(2,6,10)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(2,6,10)]*is.finite(NRMSE_total[,c(2,6,10)])), na.rm=TRUE),
rowMeans((NIS_total[,c(2,6,10)]*is.finite(NIS_total[,c(2,6,10)])), na.rm=TRUE))
   
    M_trimestre3[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = cbind(rowMeans((NRMSE_test[,c(3,7,11)]*is.finite(NRMSE_test[,c(3,7,11)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(3,7,11)]*is.finite(NIS_test[,c(3,7,11)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(3,7,11)]*is.finite(NRMSE_total[,c(3,7,11)])), na.rm=TRUE),
rowMeans((NIS_total[,c(3,7,11)]*is.finite(NIS_total[,c(3,7,11)])), na.rm=TRUE))
    
     M_trimestre4[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = cbind(rowMeans((NRMSE_test[,c(4,8,12)]*is.finite(NRMSE_test[,c(4,8,12)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(4,8,12)]*is.finite(NIS_test[,c(4,8,12)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(4,8,12)]*is.finite(NRMSE_total[,c(4,8,12)])), na.rm=TRUE),
rowMeans((NIS_total[,c(4,8,12)]*is.finite(NIS_total[,c(4,8,12)])), na.rm=TRUE))
  
                                                            
  
  
  
}



```



## Resultados de métricas

```{r}
Metricas = as.data.frame(cbind(unlist(Grupos),Metricas))
colnames(Metricas) = c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
Metricas

save(Metricas, file = "Validación2018.Rdata")
getwd()
write_xlsx(Metricas,"C:/Users/usuario1/Desktop/CIMPA/Github_CIMPA/PRACTICA_CIMPA/Trabajo Individual/Validación2018.xlsx")


M_trimestre1 = as.data.frame(cbind(unlist(Grupos),M_trimestre1))
colnames(M_trimestre1) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M_trimestre1

M_trimestre2 = as.data.frame(cbind(unlist(Grupos),M_trimestre2))
colnames(M_trimestre2) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M_trimestre2

M_trimestre3 = as.data.frame(cbind(unlist(Grupos),M_trimestre3))
colnames(M_trimestre3) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M_trimestre3

M_trimestre4 = as.data.frame(cbind(unlist(Grupos),M_trimestre4))
colnames(M_trimestre4) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M_trimestre4


save(M_trimestre1, file = "M_trimestre1_2018.Rdata")
save(M_trimestre2, file = "M_trimestre2_2018.Rdata")
save(M_trimestre3, file = "M_trimestre3_2018.Rdata")
save(M_trimestre4, file = "M_trimestre4_2018.Rdata")
```

# Validación tipo 2 2010-2012

## Entrenamiento y predicciones

```{r}
    
Metricas2 = matrix(nrow = length(Cantones), ncol = 4)
M2_trimestre1 = matrix(nrow = length(Cantones), ncol = 4)
M2_trimestre2 = matrix(nrow = length(Cantones), ncol = 4)
M2_trimestre3 = matrix(nrow = length(Cantones), ncol = 4)
M2_trimestre4 = matrix(nrow = length(Cantones), ncol = 4)

Index = c(1,4,7,10,13,16,18,20,23,25,28,30)

val_a = unique(X_data$Year)[c(10,11,12)]
val_a = rep(val_a, each = 4)


val_m = sort(unique(X_data$Month))
val_indx = rep(c(1,4,7,10), 3)


for (i in 1:length(Grupos)) {
  
  X_grupo = X_data %>% filter(Canton %in% Grupos[[i]])
  y_grupo = y_data %>% filter(Canton %in% Grupos[[i]])
  
  
  NRMSE_test = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
  NIS_test = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
      
  NRMSE_total = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
  NIS_total = matrix(nrow = length(Grupos[[i]]), ncol = length(val_a))
  

  for (v in 1:length(val_a)) {
    
    Xtrain = X_grupo %>% filter(Year < val_a[v])
    Xtrain = rbind(Xtrain, h=X_grupo %>% filter(Year == val_a[v] & Month < val_m[val_indx[v]]))
    
    ytrain = y_grupo %>% filter(Year < val_a[v])
    ytrain =  rbind(ytrain, y_grupo %>% filter(Year == val_a[v] & Month < val_m[val_indx[v]]))
    
    Xtest = X_grupo %>% filter(Year == val_a[v] & Month %in% val_m[val_indx[v]:(val_indx[v]+2)] )
    ytest = y_grupo %>% filter(Year == val_a[v] & Month %in% val_m[val_indx[v]:(val_indx[v]+2)] )
    
    
    model %>% compile(loss = "mse", 
                      optimizer = optimizer_adam(lr = 0.0005),
                      metric = "mean_absolute_error")
    
    trained_model <- model %>% fit(
      x =  as.matrix(Xtrain[,-1]), 
      y = as.matrix(ytrain[,c("RR")]), 
      batch_size = 18, 
      epochs = 40, 
      validation_split = 0.1,
      shuffle = F) 
    
  
    for (j in 1:length(Grupos[[i]])) {
      

      pred = NULL
      
      xtr = Xtrain %>% filter(Canton == Grupos[[i]][j])
      xtr = as.matrix(xtr[,-1])
      
      xts = Xtest %>% filter(Canton == Grupos[[i]][j])
      xts = as.matrix(xts[,-1])
      
      base = data.frame(basecanton2 %>% filter(Canton == Grupos[[i]][j]) %>% dplyr::select(RR))
    
      yts = as.matrix(denorm((ytest %>% filter(Canton == Grupos[[i]][j]))[,-c(1,2,3)], base))
        
      # predicciones a 3 meses
      for (k in 1:2) {
        pred[k] = predice(xts)[k]
        xts[k+1,21] = pred[k]
      } 
      pred[3] = predice(xts)[3]
      
      
     
      # Se crea una base para las predicciones, "df1", que tiene los valores predichos, los valores reales, fecha y mes.
      df1 = as.data.frame(cbind(pred, 
                                yts, 
                                Fecha[(nrow(xtr)+1):(nrow(xtr)+3)],
                                Mes[(nrow(xtr)+1):(nrow(xtr)+3)]))
      colnames(df1) = c("y_pred", "RR", "Fecha","Mes")
      df1$RR = as.numeric(df1$RR)
      df1$y_pred = as.numeric(df1$y_pred)
      
    
     
      #### VALORES APROXIMADOS ####
      ## Generar valores ajustados
      
      df2 = as.data.frame(cbind(predice(xtr), 
                                base$RR[1:nrow(xtr)], 
                                Fecha[1:nrow(xtr)], 
                                Mes[1:nrow(xtr)]))
      colnames(df2) = c("y_pred", "RR", "Fecha","Mes")
      df2$RR = as.numeric(df2$RR)
      df2$y_pred = as.numeric(df2$y_pred)
      df2 = rbind(df2, df1)
      
     # everyother1 <- function(x) x[(seq_along(Fecha) + 5)%%12 == 6]
      
      # aqui hago las predicciones del 2000 hasta el 2020 con intervalos de bootstrap
      
    LI = matrix(ncol = 1, nrow = nrow(df2))
    LS = matrix(ncol = 1, nrow = nrow(df2))
    for (w in 1:12) {

      indx = which(df2$Mes== w)
      x <- df2[Mes==w,1] # tomo el mes w con las predicciones para cada mes (es decir que tomo el mes w para los años que hayan reportados)
      x <- as.numeric(na.omit(x))
      n <- length(x) # voy a hacer un remuestreo para la cantidad de observaciones que tenga de ese mes w
      Tn <- mean(x) # saco la media para estos datos
      
      B <- 400
      Tboot_b <- NULL
      for(b in 1:B) {  
        xb <- sample(x, size = n, replace = TRUE)  
        Tboot_b[b] <- mean(xb)
      }
      # calculo de estadisticos de bootstrap
      Tboot <- mean(Tboot_b)
      Vboot <- var(Tboot_b)
      sdboot <- sqrt(Vboot)
      
      # ahora el IC de bootstrap estudentizado
      B <- 400
      Tboot_b <- NULL
      Tboot_bm <- NULL
      sdboot_b <- NULL
      
      for (b in 1:B) {  
        xb <- sample(x, size = n, replace = TRUE)  
        Tboot_b[b] <- mean(xb) # la media
        for (m in 1:B) {    
          xbm <- sample(xb, size = n, replace = TRUE)    
          Tboot_bm[m] <- mean(xbm)  
        }  
        sdboot_b[b] <- sd(Tboot_bm)
      }
      
      z_star <- (Tboot_b - Tn) / sdboot_b
      
      # se crean los limites inferiores y superiores
      LI[indx,] = x - quantile(z_star, 1 - 0.05 / 2) * sdboot
      LS[indx,] = x - quantile(z_star, 0.05 / 2) * sdboot
    }
    
      
      
      
      #Añadir límites a la base df2
      
    
      df2 = cbind(df2, LI, LS)
      df1 = cbind(df1, LI[(nrow(xtr)+1):(nrow(xtr)+3)], 
                  LS[(nrow(xtr)+1):(nrow(xtr)+3)])
      colnames(df1) = c("y_pred","RR","Fecha","Mes","LI","LS")
    
      
      NRMSE_test[j,v] = as.numeric(nrmse(df1))
      
      NIS_test[j,v] = as.numeric(nis(df1))
      
      NRMSE_total[j,v] = as.numeric(nrmse(df2))

      NIS_total[j,v] = as.numeric(nis(df2))
  
    }
    
   k_clear_session()
   
  }
  

  
  Metricas2[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = cbind( rowMeans((NRMSE_test*is.finite(NRMSE_test)), na.rm=TRUE), 
rowMeans((NIS_test*is.finite(NIS_test)), na.rm=TRUE), 
rowMeans((NRMSE_total*is.finite(NRMSE_total)), na.rm=TRUE),
rowMeans((NIS_total*is.finite(NIS_total)), na.rm=TRUE))
  
  
  M2_trimestre1[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = 
cbind(rowMeans((NRMSE_test[,c(1,5,9)]*is.finite(NRMSE_test[,c(1,5,9)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(1,5,9)]*is.finite(NIS_test[,c(1,5,9)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(1,5,9)]*is.finite(NRMSE_total[,c(1,5,9)])), na.rm=TRUE),
rowMeans((NIS_total[,c(1,5,9)]*is.finite(NIS_total[,c(1,5,9)])), na.rm=TRUE))
  
  M2_trimestre2[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = 
cbind(rowMeans((NRMSE_test[,c(2,6,10)]*is.finite(NRMSE_test[,c(2,6,10)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(2,6,10)]*is.finite(NIS_test[,c(2,6,10)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(2,6,10)]*is.finite(NRMSE_total[,c(2,6,10)])), na.rm=TRUE),
rowMeans((NIS_total[,c(2,6,10)]*is.finite(NIS_total[,c(2,6,10)])), na.rm=TRUE))
   
  M2_trimestre3[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = 
cbind(rowMeans((NRMSE_test[,c(3,7,11)]*is.finite(NRMSE_test[,c(3,7,11)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(3,7,11)]*is.finite(NIS_test[,c(3,7,11)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(3,7,11)]*is.finite(NRMSE_total[,c(3,7,11)])), na.rm=TRUE),
rowMeans((NIS_total[,c(3,7,11)]*is.finite(NIS_total[,c(3,7,11)])), na.rm=TRUE))
    
  M2_trimestre4[Index[i]:(Index[i]-1+length(Grupos[[i]])),] = 
cbind(rowMeans((NRMSE_test[,c(4,8,12)]*is.finite(NRMSE_test[,c(4,8,12)])), na.rm=TRUE), 
rowMeans((NIS_test[,c(4,8,12)]*is.finite(NIS_test[,c(4,8,12)])), na.rm=TRUE), 
rowMeans((NRMSE_total[,c(4,8,12)]*is.finite(NRMSE_total[,c(4,8,12)])), na.rm=TRUE),
rowMeans((NIS_total[,c(4,8,12)]*is.finite(NIS_total[,c(4,8,12)])), na.rm=TRUE))
  
                                                            
  
  
  
}

```



## Resultados de métricas

```{r}
Metricas2 = as.data.frame(cbind(unlist(Grupos),Metricas2))
colnames(Metricas2) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
Metricas2

save(Metricas2, file = "Validación2010.Rdata")
write_xlsx(Metricas2,"C:/Users/usuario1/Desktop/CIMPA/Github_CIMPA/PRACTICA_CIMPA/Trabajo Individual/Validación2010.xlsx")

M2_trimestre1 = as.data.frame(cbind(unlist(Grupos),M2_trimestre1))
colnames(M2_trimestre1) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M2_trimestre1

M2_trimestre2 = as.data.frame(cbind(unlist(Grupos),M2_trimestre2))
colnames(M2_trimestre2) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M2_trimestre2

M2_trimestre3 = as.data.frame(cbind(unlist(Grupos),M2_trimestre3))
colnames(M2_trimestre3) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M2_trimestre3

M2_trimestre4 = as.data.frame(cbind(unlist(Grupos),M2_trimestre4))
colnames(M2_trimestre4) =  c("Cantón", "NMRSEtest", "NIStest", "NMRSEtotal", "NIStotal")
M2_trimestre4

save(M2_trimestre1, file = "M2_trimestre1_2010.Rdata")
save(M2_trimestre2, file = "M2_trimestre2_2010.Rdata")
save(M2_trimestre3, file = "M2_trimestre3_2010.Rdata")
save(M2_trimestre4, file = "M2_trimestre4_2010.Rdata")

```

